# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blue-ridge}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Relevance"]
  s.date = %q{2010-11-30}
  s.description = %q{support for command-line and in-browser JavaScript unit tests}
  s.email = %q{tech@weplay.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "CONTRIBUTORS",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "generators/blue_ridge/blue_ridge_generator.rb",
    "generators/blue_ridge/templates/application.html",
    "generators/blue_ridge/templates/application_spec.js",
    "generators/blue_ridge/templates/screw.css",
    "generators/blue_ridge/templates/spec_helper.js",
    "generators/javascript_spec/javascript_spec_generator.rb",
    "generators/javascript_spec/templates/fixture.html.erb",
    "generators/javascript_spec/templates/javascript_spec.js.erb",
    "lib/blue-ridge.js",
    "lib/blue_ridge.rb",
    "lib/command-line.js",
    "lib/consoleReportForRake.js",
    "lib/report.js",
    "lib/shell.js",
    "lib/tasks/javascript_testing_tasks.rake",
    "lib/test_runner.js",
    "spec/javascripts/blue_ridge_browser_spec.js",
    "spec/javascripts/blue_ridge_command_line_spec.js",
    "spec/javascripts/fixtures/blue_ridge_browser.html",
    "spec/javascripts/fixtures/blue_ridge_command_line.html",
    "spec/javascripts/fixtures/partials/foobar.html",
    "spec/javascripts/fixtures/screw.unit/screw.behaviors.html",
    "spec/javascripts/fixtures/screw.unit/screw.matchers.html",
    "spec/javascripts/fixtures/screw.unit/screw.print.html",
    "spec/javascripts/fixtures/smoke/core.html",
    "spec/javascripts/fixtures/smoke/mock.html",
    "spec/javascripts/fixtures/smoke/screw_integration.html",
    "spec/javascripts/fixtures/smoke/stub.html",
    "spec/javascripts/screw.unit/screw.behaviors_spec.js",
    "spec/javascripts/screw.unit/screw.matchers_spec.js",
    "spec/javascripts/screw.unit/screw.print_spec.js",
    "spec/javascripts/smoke/core_spec.js",
    "spec/javascripts/smoke/mock_spec.js",
    "spec/javascripts/smoke/screw_integration_spec.js",
    "spec/javascripts/smoke/stub_spec.js",
    "spec/javascripts/spec_helper.js",
    "spec/rubies/blue_ridge_spec.rb",
    "spec/rubies/spec_helper.rb",
    "vendor/LICENSE-Screw.Unit",
    "vendor/LICENSE-Smoke",
    "vendor/env-js.jar",
    "vendor/env.rhino.js",
    "vendor/jquery-1.3.2.js",
    "vendor/jquery-1.4.2.js",
    "vendor/jquery.fn.js",
    "vendor/jquery.print.js",
    "vendor/screw.behaviors.js",
    "vendor/screw.builder.js",
    "vendor/screw.events.js",
    "vendor/screw.matchers.js",
    "vendor/screw.mocking.js",
    "vendor/smoke.core.js",
    "vendor/smoke.mock.js",
    "vendor/smoke.stub.js"
  ]
  s.homepage = %q{http://github.com/weplay/blue-ridge}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{support for command-line and in-browser JavaScript unit tests}
  s.test_files = [
    "spec/rubies/blue_ridge_spec.rb",
    "spec/rubies/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

